### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by sc20099** [TrentPierce/Ethereum-Address-Collider#1]
C:\python3.8\Ethereum-Address-Collider-master>python38 ethcollider.py
  File "ethcollider.py", line 24
    R = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141L
                                                                          ^
SyntaxError: invalid syntax

**Comment by antonios988** [comment]
have some problem
