### ISSUE TITLE
Has anyone successfully collided?

### ISSUE THREAD

**Issue by GreenJoson** [TrentPierce/Ethereum-Address-Collider#2]
Has anyone successfully collided?

**Comment by ilyesm** [comment]
`  File "*/Ethereum-Address-Collider/EthCollider.py", line 50
    r = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141L
                                                                          ^
SyntaxError: invalid synta`

**Comment by hibana2077** [comment]
Code has some problem,you can fix it by yourself.

**Comment by TrentPierce** [comment]
> Has anyone successfully collided?

Not that I am aware of. This project is also outdated, but the idea still remains the same.
